# Numpy Practice Session

In [2]:
# import numpy
import numpy as np

# Creating an array by usnig numpy

In [4]:
# 1-D Array
food = np.array(['Pakora','Samosa','Raita'])
food
type(food)

numpy.ndarray

In [5]:
price = np.array([5,5,5])
price
type(price)

numpy.ndarray

In [6]:
len(food)

3

In [7]:
price.mean()

5.0

In [8]:
# Zeros
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [9]:
# Ones
np.ones(5)

array([1., 1., 1., 1., 1.])

In [13]:
# empty
np.empty(5)

array([1., 1., 1., 1., 1.])

In [14]:
# range
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
# specify
np.arange(2,20)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [16]:
# specific interval
np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [17]:
# table of 5
np.arange(5,55,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [20]:
# line space
np.linspace(1,10,num=5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [21]:
# specify your data type
np.ones(5,  dtype=np.int64)

array([1, 1, 1, 1, 1], dtype=int64)

In [22]:
np.ones(5,  dtype=np.float64)

array([1., 1., 1., 1., 1.])

# Array Functions


In [24]:
a=np.array([10,12,115,2,4,6,100,320,.5,10.3])
a

array([ 10. ,  12. , 115. ,   2. ,   4. ,   6. , 100. , 320. ,   0.5,
        10.3])

In [26]:
a.sort()
a

array([  0.5,   2. ,   4. ,   6. ,  10. ,  10.3,  12. , 100. , 115. ,
       320. ])

# 2-D Array

In [27]:
a = np.array([[1,2,3,4,5],[5,4,3,2,1]])
a

array([[1, 2, 3, 4, 5],
       [5, 4, 3, 2, 1]])

In [35]:
b = np.array([[5,6,7,8,9],[9,8,7,6,5]])
b

array([[5, 6, 7, 8, 9],
       [9, 8, 7, 6, 5]])

In [39]:
c = np.concatenate((a,b), axis=0)
c

array([[1, 2, 3, 4, 5],
       [5, 4, 3, 2, 1],
       [5, 6, 7, 8, 9],
       [9, 8, 7, 6, 5]])

In [40]:
c = np.concatenate((a,b), axis=1)
c

array([[1, 2, 3, 4, 5, 5, 6, 7, 8, 9],
       [5, 4, 3, 2, 1, 9, 8, 7, 6, 5]])

In [42]:
a =  np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [43]:
a.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [44]:
a.ndim


1

In [45]:
a = np.array([1,2,3,4,5,6,7,8,9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
a.shape

(9,)

In [48]:
# Rowwise 2-D conversion
b = a[np.newaxis,:]
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [49]:
b.shape

(1, 9)

In [50]:
# Column wise 2-D Conversion
c = a[:,np.newaxis]
c

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])